version: "3"

services:

  etracs-web:
    container_name: etracs-web
    image: ramesesinc/etracs-web:255.03.001
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_custom/env.conf
    ports:
      - "8080:8080"
