version: "3"

services:
  
  notification-socketio:
    container_name: notification-socketio
    image: "ramesesinc/notification-server:1.0"
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "7080:8080"


  notification-ws60:
    container_name: notification-ws60
    image: ramesesinc/notification-ws:255.03
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
      topic_channels: "user,group,others,etracs,queue"
    ports:
      - "8060:8060"


  notification-ws61:
    container_name: notification-ws61
    image: ramesesinc/notification-ws:255.03
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
      topic_channels: "user,group,others,etracs"
    ports:
      - "8061:8060"
